@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package random832.itemarrows.datagen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
